# Практическое занятие 8
# Компьютерный практикум по алгебре на Python
## Численное решение систем линейных алгебраических уравнений (СЛАУ) с numpy.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [1]:
import numpy as np
from numpy import linalg
from google.colab import files
import pandas as pd

### Задание 1.
Решить СЛАУ с помощью linalg.solve() и выполнить проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+4y+3z=18\\
5x-y+4z=81\\
-3x+5y+5z=21
\end{matrix}
\right.
$$

In [ ]:
A = np.array([[-1, 4, 3], [5, -1, 4], [-3, 5, 5]])
b = np.array([18, 81, 21])
X = linalg.solve(A, b)
print(f'Решение СЛАУ {X}')

Решение СЛАУ [ 8. -1. 10.]


In [ ]:
np.allclose(A @ X, b)

True

### Задание 2.
Определить с помощью Теоремы Кронекера-Капелли и linalg.matrix_rank, совместны ли СЛАУ
$$
a)\ \left\{
\begin{matrix}
-x + 4y + 3z = 18\\
5x - y + 4z = 81\\
8x - 13y - 5z = 2
\end{matrix}
\right.
b)\ \left\{
\begin{matrix}
-x + 4y + 3z = 18\\
5x - y + 4z = 81\\
8x - 13y - 5z = 27
\end{matrix}
\right.
c)\ \left\{
\begin{matrix}
-x + 4y + 3z = 18\\
5x - y + 4z = 81\\
8x - 13y - z = 27
\end{matrix}
\right.
$$

Сделать вывод о числе решений каждой СЛАУ (текстом)

In [2]:
A = np.array([[-1, 4, 3], [5, -1, 4], [8, -13, -5]])
a = np.array([18, 81, 2])
print(f'Rg(А) = {linalg.matrix_rank(A)}')

Rg(А) = 2


In [9]:
Aa = np.column_stack((A, a))
print(f'Rg(Аb) = {linalg.matrix_rank(Aa)}')
print(f'Cистема {"не " * int(linalg.matrix_rank(A) < linalg.matrix_rank(Aa))}совместна')

Rg(Аb) = 3
Cистема не совместна


In [8]:
B = np.array([[-1, 4, 3], [5, -1, 4], [8, -13, -5]])
b = np.array([18, 81, 27])
print(f'Rg(B) = {linalg.matrix_rank(B)}')

Rg(B) = 2


In [7]:
Bb = np.column_stack((B, b))
print(f'Rg(Bb) = {linalg.matrix_rank(Bb)}')
print(f'Cистема {"не " * int(linalg.matrix_rank(B) < linalg.matrix_rank(Bb))}совместна')
print(f'Cистема имеет {"бесконечное число решений" if linalg.matrix_rank(B) != 3 else "единственное решение"}')

Rg(Bb) = 2
Cистема совместна
Cистема имеет бесконечное число решений


In [11]:
C = np.array([[-1, 4, 3], [5, -1, 4], [8, -13, -1]])
c = np.array([18, 81, 27])
print(f'Rg(С) = {linalg.matrix_rank(C)}')

Rg(С) = 3


In [13]:
Cc = np.column_stack((C, c))
print(f'Rg(Сb) = {linalg.matrix_rank(Cc)}')
print(f'Cистема {"не " * int(linalg.matrix_rank(C) < linalg.matrix_rank(Cc))}совместна')
print(f'Cистема имеет {"бесконечное число решений" if linalg.matrix_rank(C) != 3 else "единственное решение"}')

Rg(Сb) = 3
Cистема совместна
Cистема имеет единственное решение


### Задание 3
Описать функцию print_info с обязательным аргументом **$Ab$** - расширенной матрицей СЛАУ и необязательным аргументом  **end** (по умолчанию "\n", его нужно передавать функции print как ее  необязательный аргумент end), выводящую на экран

1) матрицу левой части СЛАУ

2) столбец правой части СЛАУ

3) транспонированную матрицу, полученную в 1)

4) расширенную матрицу, полученную из матрицы 3) и столбца 2)

5) созданную на основе списочного выражения np.array $3\times 4$ из расположенных в шахматном порядке чисел $a$ и $-a$, где $a$ - правый нижний элемент матрицы 3).

Применить полученную функцию к расширенным матрицам СЛАУ из Задания 2 со значением **end="\\n\\n"**, а затем  **end** по умолчанию.

In [14]:
def print_info(Ab, end = "\n"):
  A1 = Ab[:,range(0,3)]
  print("1) Матрицa левой части:")
  print(A1, end=end)
  b1 = Ab[:,-1]
  print("2) Столбец правой части:")
  print(b1, end=end)
  A1 = np.transpose(A1)
  print("3) Транспонированная матрица, полученная в пункте 1):")
  print(A1, end=end)
  Ab_1 = np.column_stack((A1, b1))
  print("4) Расширенная матрица из матрицы 3) и столбца 2):")
  print(Ab_1, end=end)
  A = np.array([[A1[2][2] if (i + j) % 2 == 0 else A1[2][2] * -1 for i in range(4)]for j in range(3)])
  print("5) np.array в шахматном порядке:")
  print(A, end= end)

In [15]:
print_info(Aa, end="\n\n")

1) Матрицa левой части:
[[ -1   4   3]
 [  5  -1   4]
 [  8 -13  -5]]

2) Столбец правой части:
[18 81  2]

3) Транспонированная матрица, полученная в пункте 1):
[[ -1   5   8]
 [  4  -1 -13]
 [  3   4  -5]]

4) Расширенная матрица из матрицы 3) и столбца 2):
[[ -1   5   8  18]
 [  4  -1 -13  81]
 [  3   4  -5   2]]

5) np.array в шахматном порядке:
[[-5  5 -5  5]
 [ 5 -5  5 -5]
 [-5  5 -5  5]]



In [16]:
print_info(Bb, end="\n\n")

1) Матрицa левой части:
[[ -1   4   3]
 [  5  -1   4]
 [  8 -13  -5]]

2) Столбец правой части:
[18 81 27]

3) Транспонированная матрица, полученная в пункте 1):
[[ -1   5   8]
 [  4  -1 -13]
 [  3   4  -5]]

4) Расширенная матрица из матрицы 3) и столбца 2):
[[ -1   5   8  18]
 [  4  -1 -13  81]
 [  3   4  -5  27]]

5) np.array в шахматном порядке:
[[-5  5 -5  5]
 [ 5 -5  5 -5]
 [-5  5 -5  5]]



In [17]:
print_info(Cc, end="\n\n")

1) Матрицa левой части:
[[ -1   4   3]
 [  5  -1   4]
 [  8 -13  -1]]

2) Столбец правой части:
[18 81 27]

3) Транспонированная матрица, полученная в пункте 1):
[[ -1   5   8]
 [  4  -1 -13]
 [  3   4  -1]]

4) Расширенная матрица из матрицы 3) и столбца 2):
[[ -1   5   8  18]
 [  4  -1 -13  81]
 [  3   4  -1  27]]

5) np.array в шахматном порядке:
[[-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]]



### Задание 4.
Исследовать на совместность СЛАУ с параметром $a$ при значениях параметра $a=-1$, $a=0$ и $a=1$ и найти решение, если оно единственно и провести проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+5y-3z=8a\\
4x-ay+5z=-a\\
3x+4y+2z=5a
\end{matrix}
\right.
$$
**Указание** - описать функцию check_SLAE от аргументов $A$ и $b$ (матрица левой части и столбец правой части), которая возвращает 0 для несовместной СЛАУ, 1 для совместной СЛАУ с единственным решением и 2 в остальных случаях.

Затем в цикле по значениям параметра $a$ проверять с помощью check_SLAE совместность и единственность решения СЛАУ и выводить на экран значение параметра и решение СЛАУ, если оно существует и единственно или "решений нет" или "решение не единственно".

In [18]:
def check_SLAE(A, b):
  matrix = np.column_stack((A, b))
  rng_A = np.linalg.matrix_rank(A)
  rng_matrix = np.linalg.matrix_rank(matrix)
  if (rng_A == rng_matrix) and (rng_matrix == A.shape[0]):
    res = linalg.solve(A, b)
    print(f"Решение СЛАУ:")
    display(res)
    return 1
  elif  (rng_A == rng_matrix) and (rng_matrix != A.shape[0]):
    print("Решение не единственно")
    return 2
  else:
    print("Решений нет")
    return 0

In [19]:
params = {-1: np.array([[-1, 5, -3],
                        [4, 1, 5],
                        [3, 4, 2]]),
          0: np.array([[-1, 5, -3],
                      [4, 0, 5],
                      [3, 4, 2]]),
          1: np.array([[-1, 5, -3],
                      [4, -1, 5],
                      [3, 4, 2]])}

In [21]:
for a in params:
    A = params[a]
    b = np.array([8 * a, -1 * a, 5 * a])
    print(f'При a = {a}:')
    check_SLAE(A, b)

При a = -1:
Решение СЛАУ:


array([-1.28571429, -1.        ,  1.42857143])

При a = 0:
Решение СЛАУ:


array([ 0.,  0., -0.])

При a = 1:
Решений нет


### Задание 5.
Считать из файла 'SLAE_5.xlsx' матрицу левой части и столбец правой части с листов 'A5' и 'b5' и вывести их на экран.

Решить СЛАУ $AX=b$ и вывести полученное решение на экран.

Записать полученное решение в файл  'SLAE_5.xlsx' на лист 'X5'.

Скачать полученный файл.

In [23]:
from google.colab import files
import pandas as pd
uploaded = files.upload()
for file_name in uploaded.keys():
    print(f'Загружен файл {file_name}')

Adf = pd.read_excel(file_name, sheet_name='A5', header=None)
bdf = pd.read_excel(file_name, sheet_name='b5', header=None)
print(Adf, bdf, sep='\n')

Saving SLAE_5.xlsx to SLAE_5 (1).xlsx
Загружен файл SLAE_5 (1).xlsx
    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
0   -1   6   9  -1  -3  -8   9   9   1   6  -3   1   6  -3  -2   6   6  -7
1    3   5   0   8   3  -1 -10   9 -10   3  -9  -1   5   9   8  -9  -7   5
2    4   2  -3  -4  -9   3   9   5  -4   8  -4   1 -10   9  -3  -6  -5  -4
3   -7  -9  -5   4   3  -6  -6   7 -10   0   3  -7  -4  -7 -10   8   9   0
4    9  -1   7   9  -8  -2   6   0   3   3  -3  -3  -8  -6  -6  -7   2   0
5   -3   0   3   1  -6 -10  -8  -9  -7   7   6   6   1 -10   6  -7   6   1
6   -1  -6   8  -1   1  -7 -10   7 -10   3   2   6   2   0  -1 -10   6   3
7   -6  -5  -6   5   5  -7   0  -8   3  -2  -7  -2   0   1  -5  -4  -9  -9
8   -8   2  -8   9  -3   5  -5  -6   1   7   8  -3   1   6  -5   6   9  -2
9   -7   7   2  -9   4  -4  -8  -7   4   1  -9   9  -5   5  -6   4   2   0
10  -2  -2   7 -10  -3  -5 -10   8  -6   2  -9   1  -2   2  -3  -6  -5  -4
11   8  -2  -5 -10  -1  -2   8  

In [26]:
Adf_n = Adf.to_numpy()
bdf_n = bdf.to_numpy()
print("Mатрица левой части A5:")
print(Adf_n)
print("Cтолбец правой части b5:")
print(bdf_n)

Mатрица левой части A5:
[[ -1   6   9  -1  -3  -8   9   9   1   6  -3   1   6  -3  -2   6   6  -7]
 [  3   5   0   8   3  -1 -10   9 -10   3  -9  -1   5   9   8  -9  -7   5]
 [  4   2  -3  -4  -9   3   9   5  -4   8  -4   1 -10   9  -3  -6  -5  -4]
 [ -7  -9  -5   4   3  -6  -6   7 -10   0   3  -7  -4  -7 -10   8   9   0]
 [  9  -1   7   9  -8  -2   6   0   3   3  -3  -3  -8  -6  -6  -7   2   0]
 [ -3   0   3   1  -6 -10  -8  -9  -7   7   6   6   1 -10   6  -7   6   1]
 [ -1  -6   8  -1   1  -7 -10   7 -10   3   2   6   2   0  -1 -10   6   3]
 [ -6  -5  -6   5   5  -7   0  -8   3  -2  -7  -2   0   1  -5  -4  -9  -9]
 [ -8   2  -8   9  -3   5  -5  -6   1   7   8  -3   1   6  -5   6   9  -2]
 [ -7   7   2  -9   4  -4  -8  -7   4   1  -9   9  -5   5  -6   4   2   0]
 [ -2  -2   7 -10  -3  -5 -10   8  -6   2  -9   1  -2   2  -3  -6  -5  -4]
 [  8  -2  -5 -10  -1  -2   8  -5  -1   7  -5   1   1 -10  -4   2   0  -5]
 [  1   4  -8 -10  -1   2   1   0   3   2   0   1   9  -8  -2  -5   5  -8]
 

In [28]:
X = linalg.solve(Adf_n, bdf_n)
print(f'Решение СЛАУ: \n {X}')
Xdf = pd.DataFrame(X)
with pd.ExcelWriter(file_name, mode='a') as writer:
    Xdf.to_excel(writer, sheet_name='X5', header=False, index=False)
files.download(file_name)

Решение СЛАУ: 
 [[-1.]
 [ 6.]
 [ 6.]
 [-1.]
 [-7.]
 [ 8.]
 [ 9.]
 [-6.]
 [-3.]
 [-6.]
 [ 1.]
 [ 6.]
 [-4.]
 [ 8.]
 [ 9.]
 [ 3.]
 [ 7.]
 [ 4.]]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

### Индивидуальное задание. Вариант №191

Исследовать на совместность СЛАУ с параметром $a$ при заданных значениях параметра $a$ и найти решение, если оно единственно и провести проверку подстановкой.

На листы 'A1', 'A2' и т.п. файла 'Name_Ind_8_SLAE.xlsx' записать матрицы при заданных значениях параметра $a$, на листы 'b1', 'b2' и т.п. столбцы правой части СЛАУ, на листы 'X1', 'X2' и т.п. решения СЛАУ (если оно существует!).


In [35]:
from google.colab import files
import pandas as pd

In [36]:
def check_SLAE(A,b):
  matrix = np.column_stack((A, b))
  rng_A = np.linalg.matrix_rank(A)
  rng_matrix = np.linalg.matrix_rank(matrix)
  if (rng_A == rng_matrix) and (rng_matrix == A.shape[0]):
    res = linalg.solve(A, b)
    return 1
  elif  (rng_A == rng_matrix) and (rng_matrix != A.shape[0]):
    return 2
  else:
    return 0

In [41]:
uploaded = files.upload()
for file_name in uploaded.keys():
    print(f'Загружен файл {file_name}')

Saving Iarovitsyna_Ind_8_SLAE.xlsx to Iarovitsyna_Ind_8_SLAE (1).xlsx
Загружен файл Iarovitsyna_Ind_8_SLAE (1).xlsx


In [42]:
params = {-2: np.array([[3, -2, 2, 1],
                        [3, 3, 2, 1],
                        [3, 2, 1, 4],
                       [2, 4, 4, 1]
                       ]),
          2: np.array([[3, 2, 2, 1],
                        [3, 3, 2, 1],
                        [3, 2, 1, 4],
                       [2, 4, 4, 1]]),
          7: np.array([[3, 7, 2, 1],
                        [3, 3, 2, 1],
                        [3, 2, 1, 4],
                       [2, 4, 4, 1]])}

In [43]:
c = 0
for a in params:
  A = params[a]
  b = np.array([8, 11, 6, a])
  print(f'При значение параметра a = {a}, функция возвращает:')
  result = check_SLAE(A, b)
  Adf = pd.DataFrame(A)
  with pd.ExcelWriter(file_name, mode='a') as writer:
    Adf.to_excel(writer, sheet_name=f'A{c + 1}', header=False, index=False)
  Bdf = pd.DataFrame(b)
  with pd.ExcelWriter(file_name, mode='a') as writer:
    Bdf.to_excel(writer, sheet_name=f'b{c + 1}', header=False, index=False)
  if result == 1:
    solution = linalg.solve(A, b)
    print(f'Проверка решения при  -  {solution}')
    print(np.allclose(A @ solution, b))
    Sol_df = pd.DataFrame(solution)
    with pd.ExcelWriter(file_name, mode='a') as writer:
      Sol_df.to_excel(writer, sheet_name=f'X{c + 1}', header=False, index=False)
  elif result == 2:
    print("Бесконечное множество решений")
  elif result == 0:
    print("СЛАУ не имеет решений")
  c+=1
files.download(file_name)

При значение параметра a = -2, функция возвращает:
Проверка решения при  -  [ 6.368  0.6   -3.616 -2.672]
True
При значение параметра a = 2, функция возвращает:
Проверка решения при  -  [ 4.  3. -4. -2.]
True
При значение параметра a = 7, функция возвращает:
Проверка решения при  -  [ 4.55 -0.75  0.65 -1.7 ]
True


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>